import { describe, it, expect } from 'vitest';
import { GalacticMap } from '../GalacticMap.js';
import { StarSystemGenerator } from '../StarSystemGenerator.js';
import { ExoticOverlay } from '../ExoticOverlay.js';

/**
 * AC3/AC4 known-planet immunity suite (real-universe-overlay-2026-07-12,
 * Increment 3, design D3). Injected real planets (`p.known === true`) must
 * survive every post-injection reshaping pass so a real system's observed
 * planets are never destroyed, retyped, reorbited, resonance-snapped, culled by
 * a rolled/forced binary's critical radius, or regenerated by the exotic
 * overlay. Procgen systems carry no knowns, so each guard is a no-op there (the
 * AC8 seed-stream isolation is preserved by construction — pinned separately by
 * ProcgenSnapshot.test.js). Cap + design cited by these tests:
 *   docs/WORKSTREAMS/real-universe-overlay-2026-07-12/increment-3-design.md (D3)
 *   docs/WORKSTREAMS/real-universe-overlay-2026-07-12/representation-cap.md (§5)
 *
 * Each scenario is exercised through the real generator (no mocks) with a seed
 * verified (scratch exploration) to actually TRIGGER the pass under test — i.e.
 * these fail if the guard is removed — and re-generated twice for determinism.
 */

const MASTER_SEED = 'well-dipper-galaxy-1';
const POS = { x: 8.0, y: 0.025, z: -0.001 };
const baseCtx = () => new GalacticMap(MASTER_SEED).deriveGalaxyContext(POS);
const rt = (o) => JSON.parse(JSON.stringify(o)); // round-trip (drops undefined, keeps null)

describe('D3 — forced binary + tight knowns survive the stability cull AND the slot break', () => {
  // M primary (luminosity 0.04 → maxOrbitAU = 50·√0.04 = 10 AU) with a forced
  // close companion at 5 AU: minInnerOrbitAU = 5·2.5 = 12.5 AU > maxOrbitAU, so
  // the procgen orbit loop would break at i=0 (fact 6) — yet all three KNOWN
  // slots must still be created (slot guarantee), and all three tight planets
  // (0.011–0.021 AU, deep inside the a_crit = 10 AU stability limit) must survive
  // the binary-stability cull (D3). Without the guards the system is planetless.
  const KNOWNS = [
    { letter: 'b', name: 'X b', periodDays: null, smaAU: 0.011, massEarth: 1.0, radiusEarth: 1.0, eccen: 0.01 },
    { letter: 'c', name: 'X c', periodDays: null, smaAU: 0.015, massEarth: 1.1, radiusEarth: 1.05, eccen: null },
    { letter: 'd', name: 'X d', periodDays: null, smaAU: 0.021, massEarth: 0.8, radiusEarth: 0.9, eccen: 0.02 },
  ];
  const build = () => {
    const ctx = baseCtx();
    ctx.starTypeOverride = 'M';
    ctx.companionSpec = {
      name: 'X', kind: 'multiple',
      components: [{ name: 'X', class: 'M5V' }, { name: 'X B', class: 'DA2', separationAU: 5 }],
    };
    ctx.knownPlanets = KNOWNS;
    return ctx;
  };

  it('keeps every tight known inside a_crit, at its real orbit, with real params', () => {
    const sys = StarSystemGenerator.generate('fb-1', build());
    expect(sys.isBinary).toBe(true);
    expect(sys.binarySeparationAU).toBe(5);
    // a_crit is well outside every known orbit — proving the cull would remove
    // them all if they were not immune.
    expect(sys.binaryStability.stabilityLimitAU).toBeGreaterThan(0.021);
    const known = sys.planets.filter((p) => p.known);
    expect(known.map((p) => p.letter)).toEqual(['b', 'c', 'd']);
    expect(known.map((p) => p.orbitRadiusAU)).toEqual([0.011, 0.015, 0.021]);
    // Real physical params preserved (radiusScene tracks radiusEarth).
    expect(known[0].planetData.radiusEarth).toBe(1.0);
    expect(known[2].planetData.massEarth).toBe(0.8);
    // Slot guarantee: all three known slots exist despite minInner > maxOrbit.
    expect(known.length).toBe(3);
  });

  it('generate twice → deep-equal systemData (revisit-stable)', () => {
    expect(rt(StarSystemGenerator.generate('fb-1', build())))
      .toEqual(rt(StarSystemGenerator.generate('fb-1', build())));
  });
});

describe('D3 — migration-prone config: knowns are never destroyed/retyped/reorbited', () => {
  // G primary; two knowns at 0.5 and 1.5 AU sit inside the migration scatter band
  // (between the hot-jupiter target ~0.03–0.11 AU and the migrant's ~9.3 AU
  // original orbit). Seed 'mg-0' DOES migrate and destroys two OTHER planets —
  // the knowns must survive at their real orbits with non-hot-jupiter types.
  const KNOWNS = [
    { letter: 'b', name: 'G b', periodDays: null, smaAU: 0.5, massEarth: 1.0, radiusEarth: 1.0, eccen: 0.01 },
    { letter: 'c', name: 'G c', periodDays: null, smaAU: 1.5, massEarth: 1.1, radiusEarth: 1.05, eccen: null },
  ];
  const build = () => {
    const ctx = baseCtx();
    ctx.starTypeOverride = 'G';
    ctx.knownPlanets = KNOWNS;
    return ctx;
  };

  it('migration actually occurs, yet both knowns survive unchanged', () => {
    const sys = StarSystemGenerator.generate('mg-0', build());
    expect(sys.migrationHistory.occurred).toBe(true);
    // Migration destroyed non-known planets — proof the scatter pass ran.
    expect(sys.migrationHistory.scatteredCount).toBeGreaterThan(0);
    const known = sys.planets.filter((p) => p.known);
    expect(known.map((p) => p.letter)).toEqual(['b', 'c']);
    // Real orbits untouched (not reorbited to a hot-jupiter target).
    expect(known.map((p) => p.orbitRadiusAU)).toEqual([0.5, 1.5]);
    // Never retyped to hot-jupiter (the migrant-reshape is skipped for knowns).
    for (const p of known) expect(p.planetData.type).not.toBe('hot-jupiter');
    // Real physical params preserved.
    expect(known[0].planetData.radiusEarth).toBe(1.0);
    expect(known[1].planetData.massEarth).toBe(1.1);
  });

  it('generate twice → deep-equal systemData', () => {
    expect(rt(StarSystemGenerator.generate('mg-0', build())))
      .toEqual(rt(StarSystemGenerator.generate('mg-0', build())));
  });
});

describe('D3 — resonance chain keeps every known planet at its real semi-major axis', () => {
  // M primary; three knowns near a 3:2, 3:2 chain (0.100 / 0.131 / 0.172 AU).
  // Seed 'res-16' forms a detected resonance chain (isResonant), but the snap
  // must SKIP any pair involving a known — so the archive orbits stay EXACT.
  // Without the guard, snapToResonances would rewrite orbitRadiusAU.
  const KNOWNS = [
    { letter: 'b', name: 'R b', periodDays: null, smaAU: 0.100, massEarth: 1, radiusEarth: 1, eccen: null },
    { letter: 'c', name: 'R c', periodDays: null, smaAU: 0.131, massEarth: 1, radiusEarth: 1, eccen: null },
    { letter: 'd', name: 'R d', periodDays: null, smaAU: 0.172, massEarth: 1, radiusEarth: 1, eccen: null },
  ];
  const build = () => {
    const ctx = baseCtx();
    ctx.starTypeOverride = 'M';
    ctx.knownPlanets = KNOWNS;
    return ctx;
  };

  it('a chain forms, but the knowns keep their exact real orbits', () => {
    const sys = StarSystemGenerator.generate('res-16', build());
    expect(sys.resonanceChain).not.toBeNull();
    expect(sys.resonanceChain.isResonant).toBe(true);
    const known = sys.planets.filter((p) => p.known);
    expect(known.map((p) => p.orbitRadiusAU)).toEqual([0.100, 0.131, 0.172]);
  });

  it('generate twice → deep-equal systemData', () => {
    expect(rt(StarSystemGenerator.generate('res-16', build())))
      .toEqual(rt(StarSystemGenerator.generate('res-16', build())));
  });
});

describe('D3 — exotic overlay never retypes/regenerates a known planet', () => {
  // A/B proof at the ExoticOverlay layer: an identical rocky planet in the
  // geological zone. Seed 'x230' swaps it to 'crystal' when it is a PROCGEN
  // planet, but must leave it as 'rocky' (with real params intact) when it is
  // flagged known — the candidate lists skip `p.known`. This is the mechanism
  // that preserves merged real radius/mass against _swapPlanetType regeneration.
  const makeSys = (seed, known) => ({
    seed,
    star: { type: 'K' },
    zones: { hzInnerAU: 0.5, hzOuterAU: 0.9, frostLineAU: 2.5 },
    planets: [
      {
        orbitRadiusAU: 0.3,
        orbitRadius: 30,
        planetData: {
          type: 'rocky', radiusEarth: 1.0, massEarth: 1.0, radius: 5,
          sunDirection: [1, 0, 0], atmosphere: null, moonCount: 0,
        },
        moons: [],
        ...(known ? { known: true, letter: 'b', name: 'K b' } : {}),
      },
    ],
  });

  it('the same seed swaps a procgen planet but SKIPS the known one', () => {
    const procgen = makeSys('x230', false);
    ExoticOverlay.apply(procgen);
    expect(procgen.planets[0].planetData.type).toBe('crystal'); // overlay is active on this seed

    const merged = makeSys('x230', true);
    ExoticOverlay.apply(merged);
    // Known planet untouched: original type + real radius/mass survive.
    expect(merged.planets[0].planetData.type).toBe('rocky');
    expect(merged.planets[0].planetData.radiusEarth).toBe(1.0);
    expect(merged.planets[0].planetData.massEarth).toBe(1.0);
    expect(merged.planets[0].known).toBe(true);
  });

  it('a second geological seed (shattered) is likewise skipped for a known', () => {
    const procgen = makeSys('x272', false);
    ExoticOverlay.apply(procgen);
    expect(procgen.planets[0].planetData.type).toBe('shattered');

    const merged = makeSys('x272', true);
    ExoticOverlay.apply(merged);
    expect(merged.planets[0].planetData.type).toBe('rocky');
  });

  it('applying the overlay twice to a known-bearing system is deterministic', () => {
    const a = makeSys('x230', true); ExoticOverlay.apply(a);
    const b = makeSys('x230', true); ExoticOverlay.apply(b);
    expect(rt(a)).toEqual(rt(b));
  });
});
